- name: Setup catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - catalogue

- name: Setup MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - mongodb


#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend

#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend