
- name: Setup MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - Mongodb



#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend

#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend