#- name: Setup Frontend Component
 # hosts: FRONTEND
  #become: yes
  #roles:
    - frontend

- name: Setup MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - mongodb



#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend

#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend