- name: Setup MongoDB Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - catalogue



#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend

#- name: setup frontend Component
 # hosts: all
  #roles:
   # - frontend