- name: Install Nginx
  yum:
    name: nginx
    state: latest


- name: Remove previous files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name : Copy content of the files
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes