- name: Copy the nodeJS repo file
  ansible.builtin.copy:
    src: nodejs.repo
    dest: /etc/yum.repos.d/nodejs.repo


- name: Install nodejs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add application user
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Download {{COMPONENT}} from Git repo and Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: clean old directory
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: move the catalogue files
  ansible.builtin.copy:
    src: /tmp/catalogue-main
    dest: /home/roboshop/catalogue
    remote_src: yes
  become_user: roboshop

- name: Install catalogue dependncies
  community.general.npm:
    path: /home/roboshop/catalogue/catalogue-main
  become_user: roboshop

- name: setup catalogue systemd confg files
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: start catalogue service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes

